As check failed: an Exception_ is not a int.
  0: main                      tests/negative/finally-params2-test.toit:8:23
