EXCEPTION error. 
oops
  0: main.<lambda>.<lambda>.<lambda> tests/negative/nested-throw-test.toit:9:14
