EXCEPTION error. 
nope
  0: main.<lambda>             tests/negative/task_close_test.toit:7:5
